import React from "react";

interface Categories {
  [key: string]: string[];
}

const categories: Categories = {
  ELEKTRONIK: [
    "Konsol Game",
    "Aksesoris Konsol",
    "Alat Casting",
    "Foot Bath & Spa",
    "Mesin Jahit & Aksesoris",
    "Setrika & Mesin Uap",
    "Purifier & Humidifier",
    "Penyedot Debu & Peralatan Perawatan Lantai",
    "Telepon",
    "Mesin Cuci & Pengering",
    "Water Heater",
    "Pendingin Ruangan",
    "Pengering Sepatu",
    "Penghangat Ruangan",
    "TV & Aksesoris",
    "Perangkat Dapur",
    "Lampu",
    "Kamera Keamanan",
    "Video Game",
    "Kelistrikan",
    "Baterai",
    "Remot Kontrol",
    "Walkie Talkie",
    "Media Player",
    "Perangkat Audio & Speaker",
    "Elektronik Lainnya",
  ],
  "PERLENGKAPAN RUMAH": [
    "Renovasi Rumah",
    "Perkakas",
    "Alat Pemeliharaan Rumah",
    "Kebersihan & Binatu",
    "Peralatan Dapur",
    "Peralatan Masak",
    "Peralatan Makan",
    "Alat Pengaman",
    "Organizer Rumah",
    "Perlengkapan Keagamaan",
    "Payung",
    "Pengharum Ruangan & Aromaterapi",
    "Kamar Mandi",
    "Kamar Tidur",
    "Dekorasi",
    "Furniture",
    "Taman",
    "Perlengkapan Rumah Lainnya",
  ],
  "TAS PRIA": ["Tas Selempang & Bahu Pria", "Dompet", "Ransel Pria", "Tas Pinggang Pria", "Tas Laptop", "Clutch", "Tote Bag", "Tas Kerja", "Tas Pria Lainnya"],
  "SEPATU WANITA": [
    "Boots",
    "Sneakers",
    "Sepatu Flat",
    "Loafers & Boat Shoes",
    "Sepatu Oxford",
    "Slip Ons, Mary Janes & Mules",
    "Heels",
    "Wedges",
    "Sandal",
    "Aksesoris & Perawatan Sepatu",
    "Kaus Kaki & Stocking",
    "Sepatu Wanita Lainnya",
  ],
  "OLAH RAGA & OUTDOOR": [
    "Pakaian Olahraga Anak",
    "Aksesoris Olahraga & Aktivitas Outdoor",
    "Boardsport",
    "Alat Pancing",
    "Bersepeda",
    "Camping & Hiking",
    "Panjat Tebing",
    "Panahan",
    "Sepak Bola, Futsal, & Sepak Takraw",
    "Basket",
    "Voli",
    "Bulu Tangkis",
    "Tenis",
    "Tenis Meja",
    "Tinju & Bela Diri",
    "Golf",
    "Baseball & Softball",
    "Squash",
    "Rugbi",
    "Billiard",
    "Selancar & Wakeboard",
    "Ice Skating & Olahraga Musim Dingin",
    "Diving & Renang",
    "Boating",
    "Yoga & Pilates",
    "Fitness",
    "Dart",
    "Sepatu Olahraga",
    "Pakaian Olahraga Pria",
    "Pakaian Olahraga Wanita",
    "Olahraga & Outdoor Lainnya",
  ],
  "DEALS SEKITARMU": ["Voucher ShopeePay", "Voucher Deals"],
  "MAKANAN & MINUMAN": [
    "Makanan Ringan",
    "Bahan Pokok",
    "Menu Sarapan",
    "Minuman",
    "Susu & Olahan",
    "Makanan Segar & Beku",
    "Roti & Kue",
    "Set Hadiah & Hampers",
    "Makanan Kaleng",
    "Makanan Instan",
    "Makanan & Minuman Lainnya",
  ],
  "PAKAIAN PRIA": [
    "Denim",
    "Hoodie & Sweatshirt",
    "Sweater & Cardigan",
    "Jaket, Mantel, & Rompi",
    "Jas Formal",
    "Celana Panjang",
    "Celana Pendek",
    "Atasan",
    "Batik",
    "Pakaian Dalam",
    "Pakaian Tidur",
    "Set Pakaian Pria",
    "Pakaian Tradisional",
    "Kostum",
    "Pakaian Kerja",
    "Pakaian Pria Lainnya",
  ],
  "FASHION BAYI & ANAK": [
    "Pakaian Bayi",
    "Sepatu Bayi",
    "Pakaian Anak Laki-Laki",
    "Pakaian Anak Perempuan",
    "Sepatu Anak Laki-Laki",
    "Sepatu Anak Perempuan",
    "Tas Anak Laki-Laki",
    "Tas Anak Perempuan",
    "Aksesoris Bayi & Anak",
    "Perlengkapan Hujan",
    "Perhiasan",
    "Fashion Bayi & Anak Lainnya",
  ],
  KESEHATAN: [
    "Kewanitaan",
    "Perawatan Mata",
    "Suplemen Makanan",
    "Obat-obatan & Alat Kesehatan",
    "Alat Tes & Monitor",
    "P3K",
    "Alat Bantu Cedera & Disabilitas",
    "Obat Nyamuk",
    "Popok Dewasa",
    "Hand Sanitizer",
    "Minyak Esensial",
    "Perawatan Hidung & Pernafasan",
    "Perawatan Telinga",
    "Perawatan Mulut",
    "Kesehatan Lainnya",
  ],
  "BUKU & ALAT TULIS": [
    "Alat Tulis",
    "Perlengkapan Sekolah & Kantor",
    "Folder, Organizer Kertas, & Aksesoris",
    "Perlengkapan Menggambar",
    "Buku Tulis & Kertas",
    "Surat-Menyurat",
    "Bubble Wrap",
    "Majalah & Koran",
    "Buku Anak-Anak",
    "Buku Edukasi",
    "Buku Non-Fiksi",
    "Buku Fiksi",
    "Komik & Manga",
    "E-Book",
    "Buku & Alat Tulis Lainnya",
  ],
  "KOMPUTER & AKSESORIS": [
    "Desktop",
    "Monitor",
    "Komponen Desktop & Laptop",
    "Penyimpanan Data",
    "Komponen Network",
    "Software",
    "Peralatan Kantor",
    "Printer & Scanner",
    "Aksesoris Desktop & Laptop",
    "Keyboard & Mouse",
    "Laptop",
    "Gaming",
    "Audio Computer",
    "Proyektor & Aksesoris",
    "Komputer & Aksesoris Lainnya",
  ],
  "PAKAIAN WANITA": [
    "Pakaian Tradisional",
    "Kostum",
    "Kain",
    "Batik",
    "Denim",
    "Atasan",
    "Celana Panjang & Legging",
    "Celana Pendek",
    "Rok",
    "Dress",
    "Wedding Dress",
    "Jumpsuit, Playsuit, & Overall",
    "Jaket, Mantel, & Rompi",
    "Sweater & Cardigan",
    "Hoodie & Sweatshirt",
    "Set",
    "Pakaian Dalam",
    "Pakaian Tidur & Piyama",
    "Baju Hamil",
    "Pakaian Wanita Lainnya",
  ],
  "AKSESORIS FASHION": [
    "Cincin",
    "Anting",
    "Syal & Selendang",
    "Sarung Tangan",
    "Aksesoris Rambut",
    "Gelang Tangan & Bangle",
    "Gelang Kaki",
    "Topi",
    "Kalung",
    "Kacamata & Aksesoris",
    "Lensa Kontak & Aksesoris",
    "Logam Mulia",
    "Ikat Pinggang",
    "Dasi",
    "Aksesoris Tambahan",
    "Set & Paket Aksesoris",
    "Perhiasan Berharga",
    "Aksesoris Fashion Lainnya",
  ],
  "TAS WANITA": [
    "Ransel Wanita",
    "Tas Serut",
    "Tas Laptop",
    "Clutch",
    "Tas Pinggang Wanita",
    "Tote Bag",
    "Top Handle Bag",
    "Tas Selempang & Bahu Wanita",
    "Dompet Wanita",
    "Aksesoris Tas",
    "Koper & Tas Travel",
    "Tas Wanita Lainnya",
  ],
  "SOUVENIR & PERLENGKAPAN PESTA": ["Perlengkapan Pesta", "Pembungkus Kado & Kemasan", "Souvenir & Hadiah", "Balon", "Bunga"],
  "PERAWATAN & KECANTIKAN": [
    "Perawatan Tubuh",
    "Perawatan Tangan",
    "Perawatan Kaki",
    "Perawatan Kuku",
    "Perawatan Rambut",
    "Perawatan Pria",
    "Parfum & Wewangian",
    "Kosmetik Wajah",
    "Kosmetik Mata",
    "Kosmetik Bibir",
    "Pembersih Make Up",
    "Aksesoris Make Up",
    "Alat Perawatan Wajah",
    "Alat Pelangsing Tubuh",
    "Alat Penghilang Bulu Rambut",
    "Alat Rambut",
    "Perawatan Wajah",
    "Treatment Mata",
    "Treatment Bibir",
    "Paket & Set Kecantikan",
    "Kecantikan Lainnya",
  ],
  "SEPATU PRIA": [
    "Sneakers",
    "Kaos Kaki",
    "Sandal",
    "Aksesoris & Perawatan Sepatu",
    "Boot",
    "Tali Sepatu",
    "Slip-On & Mules",
    "Sepatu Pria Lainnya",
    "Sepatu Formal",
  ],
  "IBU & BAYI": [
    "Perlengkapan Travelling Bayi",
    "Peralatan & Aksesoris Makan",
    "Perlengkapan Botol Susu",
    "Perlengkapan Menyusui",
    "Perlengkapan Ibu Hamil",
    "Kesehatan Kehamilan",
    "Kesehatan & Perawatan Bayi",
    "Perlengkapan Mandi",
    "Kamar Bayi",
    "Keamanan Bayi",
    "Susu Formula & Makanan Bayi",
    "Popok & Pispot",
    "Mainan",
    "Set & Paket Hadiah",
    "Ibu & Bayi Lainnya",
  ],
  "HOBI & KOLEKSI": [
    "Aksesoris Hewan Peliharaan",
    "Litter & Toilet",
    "Grooming Hewan",
    "Pakaian & Aksesoris Hewan",
    "Perawatan Kesehatan Hewan",
    "Makanan Hewan",
    "Koleksi",
    "Mainan & Games",
    "CD, DVD & Bluray",
    "Alat & Aksesoris Musik",
    "Piringan Hitam",
    "Album Foto",
    "Perlengkapan Menjahit",
    "Hobi & Koleksi Lainnya",
  ],
  FOTOGRAFI: [
    "Kamera",
    "Lighting & Perlengkapan Studio Foto",
    "Roll Film & Kertas Foto",
    "Printer Foto",
    "Tas & Casing Kamera",
    "Charger Baterai",
    "Baterai & Battery Grip",
    "Tripod, Monopod, & Aksesoris",
    "Kartu Memori",
    "Perawatan Kamera",
    "Drone & Aksesoris",
    "Gimbal & Stabilizer",
    "Lensa & Aksesoris",
    "Flash & Aksesoris",
    "Fotografi Lainnya",
  ],
  "HANDPHONE & AKSESORIS": [
    "Kartu Perdana",
    "Tablet",
    "Handphone",
    "Perangkat Wearable",
    "Perangkat VR",
    "Aksesoris Selfie",
    "Handphone & Tablet Aksesoris",
    "Kartu Memori",
    "Kabel, Charger, & Konverter",
    "Powerbank & Baterai",
    "Casing & Skin",
    "Audio Handphone",
    "Handphone & Aksesoris Lainnya",
  ],
  "FASHION MUSLIM": [
    "Hijab",
    "Aksesoris Muslim",
    "Atasan Muslim Wanita",
    "Dress Muslim",
    "Bawahan Muslim Wanita",
    "Mukena & Perlengkapan Sholat",
    "Pakaian Muslim Pria",
    "Pakaian Muslim Anak",
    "Outerwear",
    "Set",
    "Fashion Muslim Lainnya",
  ],
  "JAM TANGAN": ["Jam Tangan Wanita", "Jam Tangan Pria", "Jam Tangan Couple", "Aksesoris Jam Tangan", "Jam Tangan Lainnya"],
  OTOMOTIF: [
    "Mobil",
    "Aksesoris Interior Mobil",
    "Aksesoris Eksterior Mobil",
    "Suku Cadang Mobil",
    "Perkakas & Perlengkapan Kendaraan",
    "Perawatan Kendaraan",
    "Oli & Pelumas Kendaraan",
    "Gantungan & Sarung Kunci Kendaraan",
    "Sepeda Motor",
    "Aksesoris Sepeda Motor",
    "Suku Cadang Motor",
    "Aksesoris Pengendara Motor",
    "E-Money & Aksesoris",
    "Otomotif Lainnya",
  ],
  VOUCHER: ["Tiket Event", "Belanja", "Data", "Pulsa", "Travel & Tour", "Gaming", "Shopee"],
};

const FooterCategory: React.FC = () => {
  return (
    <div className="py-6">
      <h2 className="mb-4 text-sm font-medium">Kategori</h2>
      <div className="columns-2 sm:columns-3 lg:columns-5 gap-4">
        {Object.entries(categories).map(([category, items]) => (
          <div key={category} className="mb-4 break-inside-avoid-column">
            <h3 className="mb-2 text-sm font-medium">{category}</h3>
            <ul className="space-y-1">
              {items.map((item) => (
                <li key={item} className="text-xs font-normal text-neutral-600 mt-4 hover:text-orange-600 cursor-pointer">
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
};

export default FooterCategory;
